# Generated by Django 2.1 on 2018-08-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Укажите Вашу Фамилию', max_length=100, verbose_name='Фаимилия'),
        ),
    ]
