# Generated by Django 2.1 on 2018-08-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180816_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(help_text='Название модели', max_length=100, verbose_name='Название модели')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Укажите Вашу Фамилию', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gorod',
            field=models.CharField(help_text='От куда Вы, Название населенного пункта', max_length=100, verbose_name='Откуда:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Укажите Ваше Имя', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='otch_name',
            field=models.CharField(help_text='Укажите Ваше Отчество, елси есть', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sport_razyad',
            field=models.CharField(help_text='Спортивный разряд', max_length=6, verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sudeyskaja_kategorija',
            field=models.CharField(help_text='Судейская категория, если есть', max_length=6, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='ship_model',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author'),
        ),
    ]
