# Generated by Django 2.1 on 2018-08-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180816_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='ship_scale',
            field=models.CharField(default=111, help_text='В каком масштабе вполенеа модель', max_length=5, verbose_name='Масштаб'),
            preserve_default=False,
        ),
    ]
