# Generated by Django 2.1 on 2018-08-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_ship_model_ship_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='ship_scale',
            field=models.CharField(help_text='В каком масштабе вполенеа модель', max_length=5, verbose_name='Масштаб 1:'),
        ),
    ]
