# Generated by Django 2.1 on 2018-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180816_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='ship_class_naviga',
            field=models.CharField(blank=True, choices=[('F2A', 'F2A модель копия до 500 мм'), ('F2B', 'F2B модель копия до 750 мм')], default='F2A', help_text='Класс по NAVIGA', max_length=6, verbose_name='NAVIGA Класс'),
        ),
    ]
