# Generated by Django 2.1 on 2018-08-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_ship_model_ship_prototype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='new_tehno_use',
            field=models.CharField(blank=True, choices=[('---', 'Новые технологии не использовались'), ('3D PRINTER', '3D печать пластиком'), ('3D FREZA', 'ЧПУ фрезерование'), ('3D PROJECKT', '3-х мерное проектрование (готовые модели)'), ('3D PROJECKT S', '3-х мерное проектирование - самостоятельно '), ('PHOTO DETAL', 'Травление (готовые детали '), ('PHOTO DETAL S', 'Травление самостоятельно '), ('VAKUUM', 'Вакуумное формование')], default='---', help_text='Используемые современные технологии', max_length=30, verbose_name='Новые технологии'),
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='ship_class_naviga',
            field=models.CharField(blank=True, choices=[('---', 'Класс модели копии не оперделен'), ('F2A', 'F2A модель копия до 500 мм'), ('F2B', 'F2B модель копия до 750 мм'), ('F2С', 'F2С модель копия до 1600 мм'), ('F4А', 'F4А модель копия '), ('F4B', 'F4B модель копия '), ('F4С', 'F4С модель копия '), ('NSS-A', 'NSS A парусная модель копия - берудский парус'), ('NSS-B', 'NSS D парусная модель копия - гафельный парус'), ('NSS-С', 'NSS A парусная модель копия - прямые паруса'), ('NSS-D', 'NSS D парусная модель копия - много корпусные парусники')], default='---', help_text='Класс по NAVIGA', max_length=30, verbose_name='NAVIGA Класс'),
        ),
    ]
