# Generated by Django 2.1 on 2018-08-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_ship_model_new_tehno_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author', verbose_name='Автор'),
        ),
    ]
