# Generated by Django 2.1 on 2018-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180816_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(default=1, upload_to='upload/photo_author', verbose_name='Ваше фото'),
            preserve_default=False,
        ),
    ]
