# Generated by Django 2.1 on 2018-08-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_author_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='ship_prototype',
            field=models.TextField(help_text='Описание прототпа, № проекта, год постройки и т.д.', max_length=1200, verbose_name='Прототип, описание'),
        ),
    ]
