# Generated by Django 2.1 on 2018-08-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180817_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='ship_class_naviga',
            field=models.CharField(blank=True, choices=[('---', 'Класс модели копии не оперделен'), ('F2A', 'F2A модель копия до 500 мм'), ('F2B', 'F2B модель копия до 750 мм'), ('F2С', 'F2С модель копия до 1600 мм'), ('F4А', 'F4А модель копия '), ('F4B', 'F4B модель копия '), ('F4С', 'F4С модель копия '), ('NSS-A', 'NSS A парусная модель копия - берудский парус'), ('NSS-B', 'NSS D парусная модель копия - гафельный парус'), ('NSS-С', 'NSS С парусная модель копия - прямые паруса'), ('NSS-D', 'NSS D парусная модель копия - много корпусные парусники')], default='---', help_text='Класс по NAVIGA', max_length=30, verbose_name='NAVIGA Класс'),
        ),
    ]
