# Generated by Django 2.1 on 2018-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180817_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='ship_tehnology',
            field=models.CharField(blank=True, choices=[('Не использовались', 'Инновации не использовались'), ('3D PRINT', '3D печать пластиками или полимером'), ('CNC', 'Применение станков с ЧПУ'), ('CAD', 'Применение CAD ПО при разработке чертежей')], default='Не использовались', help_text='Используемые инновационные технологии', max_length=30, verbose_name='инновационные технологии'),
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='ship_class_naviga',
            field=models.CharField(blank=True, choices=[('---', 'Класс модели копии не оперделен'), ('F2A', 'F2A модель копия до 500 мм'), ('F2B', 'F2B модель копия до 750 мм'), ('F2С', 'F2С модель копия до 1600 мм'), ('F4А', 'F4А модель копия '), ('F4B', 'F4B модель копия '), ('F4С', 'F4С модель копия '), ('NSS-A', 'NSS A парусная модель копия - бермудский парус'), ('NSS-B', 'NSS D парусная модель копия - гафельный парус'), ('NSS-С', 'NSS С парусная модель копия - прямые паруса'), ('NSS-D', 'NSS D парусная модель копия - много корпусные парусники')], default='---', help_text='Класс по NAVIGA', max_length=30, verbose_name='NAVIGA Класс'),
        ),
    ]
