# Generated by Django 2.1 on 2018-08-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180826_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='date_end',
            field=models.DateField(blank=True, help_text='Дата окончания постройки', null=True, verbose_name='Дата окончания постройки'),
        ),
        migrations.AddField(
            model_name='ship_model',
            name='date_start',
            field=models.DateField(blank=True, help_text='Дата начала постройки', null=True, verbose_name='Дата начала постройки'),
        ),
    ]
