# Generated by Django 2.1 on 2018-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180826_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='ship_status',
            field=models.CharField(blank=True, choices=[('не определен', 'статус не указан'), ('Строится', 'В процесе постройки'), ('На ходу', 'На ходу'), ('Не на ходу', 'Не исправна или выработан ресурс'), ('Устрачена', 'модель утрачена, утонула, разбита и т.д.'), ('Продана', 'У модели новый владелец')], default='не определен', help_text='Текущий статус модели', max_length=30, verbose_name='Определите статус'),
        ),
        migrations.AddField(
            model_name='ship_model',
            name='ship_stend',
            field=models.CharField(default=1, help_text='Баллы на стенде', max_length=3, verbose_name='Максимальная стендовая оцентка'),
            preserve_default=False,
        ),
    ]
