# Generated by Django 2.1 on 2018-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20180828_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='photo', verbose_name='Ваше фото', width_field=100),
        ),
    ]
