# Generated by Django 2.1 on 2018-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20180828_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='ship_class_naviga',
            field=models.CharField(blank=True, choices=[('---', 'Класс модели не оперделен'), ('F2A', 'Масштабные копийные модели, длина которых не превышает 900 мм'), ('F2B', 'Масштабные копийные модели, длина которых составляет от 901 до 1400\xa0мм'), ('F2С', 'Масштабные копийные модели, длина которых не менее 1401\xa0мм'), ('F4А', 'Модель копия '), ('F4B', 'Модель копия '), ('F4С', 'Модель копия '), ('FDS', 'Модель копия с паровым двигателем'), ('NSS-A', 'Парусная модель копия - бермудский парус'), ('NSS-B', 'Парусная модель копия - гафельный парус'), ('NSS-С', 'Парусная модель копия - прямые паруса'), ('NSS-D', 'Парусная модель копия - много корпусные парусники')], default='---', help_text='Класс по NAVIGA', max_length=30, verbose_name='NAVIGA Класс'),
        ),
    ]
