# Generated by Django 2.1 on 2018-08-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20180828_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photo', verbose_name='Ваше фото'),
        ),
    ]
