# Generated by Django 2.1 on 2018-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_author_photo_author_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo_author_thumb',
        ),
        migrations.AlterField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Ваше фото'),
        ),
    ]
