# Generated by Django 2.1 on 2018-08-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20180830_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='photo_modelship',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='ship/%Y/%m/%d', verbose_name='Фото модели'),
        ),
        migrations.AddField(
            model_name='ship_model',
            name='photo_prototype',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='ship_prototype/%Y/%m/%d', verbose_name='Фото прототипа'),
        ),
    ]
