# Generated by Django 2.1 on 2018-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_remove_ship_model_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='ship_run',
            field=models.CharField(default=100, help_text='Баллы за ход', max_length=3, verbose_name='Баллы за ход'),
            preserve_default=False,
        ),
    ]
