# Generated by Django 2.1 on 2018-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_ship_model_ship_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='ship_run',
            field=models.CharField(help_text='Баллы за ход', max_length=3, verbose_name='Баллы за хода'),
        ),
    ]
