# Generated by Django 2.1 on 2018-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20180902_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fn_sportsmena',
            field=models.CharField(default=0, help_text='Ваш федеральный номер спортсмена (если есть)', max_length=7, verbose_name='федеральный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='otch_name',
            field=models.CharField(help_text='Укажите Ваше Отчество, если есть', max_length=100, verbose_name='Отчество'),
        ),
    ]
