# Generated by Django 2.1 on 2018-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20180903_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_hobby',
            field=models.CharField(default=1, help_text='Ваши интересы или дополнительная информация о себе', max_length=2000, verbose_name='Ваши интересы или дополнительная информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='ship_status',
            field=models.CharField(blank=True, choices=[('не определен', 'статус не указан'), ('Строится', 'В процесе постройки'), ('Готова', 'Процесс постройки завершон'), ('Не исправна', 'Не исправна или выработан ресурс'), ('Утрачена', 'модель утрачена, утонула, разбита и т.д.'), ('Продана', 'У модели новый владелец')], default='не определен', help_text='Текущий статус модели', max_length=30, verbose_name='Определите статус'),
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='ship_tehnology',
            field=models.CharField(blank=True, choices=[('Не использовались', 'Инновации не использовались'), ('3D PRINT', '3D печать'), ('CNC', 'Применение станков с ЧПУ'), ('CAD', 'Применение CAD ПО при разработке чертежей'), ('PHOTO', 'Фоторавление')], default='Не использовались', help_text='Используемые инновационные технологии', max_length=30, verbose_name='инновационные технологии'),
        ),
    ]
