# Generated by Django 2.1 on 2018-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20180903_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_site',
            field=models.CharField(default=1, help_text='Адрес Вашего сайта или ссылка на профиль в социальных сетях', max_length=100, verbose_name='Ваш сайт или ссылка на профиль в соц сетях'),
            preserve_default=False,
        ),
    ]
