# Generated by Django 2.1 on 2018-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_author_author_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_model',
            name='ship_stend_refery',
            field=models.CharField(default=1, help_text='Баллы на стенде', max_length=3, verbose_name='Максимальная стендовая оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='ship_stend',
            field=models.CharField(help_text='Баллы на стенде', max_length=3, verbose_name='Максимальная стендовая оценка'),
        ),
    ]
