# Generated by Django 2.1 on 2018-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20180903_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_model',
            name='ship_stend',
            field=models.CharField(help_text='Баллы на стенде', max_length=3, verbose_name='Авторская стендовая оценка'),
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='ship_stend_refery',
            field=models.CharField(help_text='Баллы на стенде', max_length=3, verbose_name='Судейская стендовая оценка'),
        ),
    ]
