# Generated by Django 2.1 on 2018-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20180903_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_hobby',
            field=models.TextField(help_text='Ваши интересы или дополнительная информация о себе', max_length=3000, verbose_name='Ваши интересы или дополнительная информация'),
        ),
    ]
