# Generated by Django 2.1 on 2018-09-15 05:51

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20180903_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photo/%Y/%m/%d', validators=[catalog.validators.validate_file_extension], verbose_name='Ваше фото'),
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='photo_modelship',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='ship/%Y/%m/%d', validators=[catalog.validators.validate_file_extension], verbose_name='Фото модели'),
        ),
        migrations.AlterField(
            model_name='ship_model',
            name='photo_prototype',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='ship_prototype/%Y/%m/%d', validators=[catalog.validators.validate_file_extension], verbose_name='Фото прототипа'),
        ),
    ]
